# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MKImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageURL', models.TextField()),
                ('Xpos', models.FloatField()),
                ('Ypos', models.FloatField()),
                ('Height', models.FloatField()),
                ('Width', models.FloatField()),
                ('Rotation', models.FloatField()),
            ],
        ),
    ]
